// Copyleft 2018 Chris Korda
// This program is free software; you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation; either version 2 of the License, or any later version.
/*
        chris korda
 
		revision history:
		rev		date	comments
		00		18jun20	initial version

        map resource IDs to help IDs
 
*/

// view IDs
{AFX_IDW_PANE_FIRST,					IDH_Views_Track_View_Track_Grid},
{CStepParent::PANE_ID_MUTE,				IDH_Views_Track_View_Track_Mutes},
{CStepParent::PANE_ID_STEP,				IDH_Views_Track_View_Track_Steps},
{CStepParent::PANE_ID_VELOCITY,			IDH_Views_Track_View_Velocities_Pane},
{CChildFrame::ID_VIEW_SONG,				IDH_Views_Song_View},
{CChildFrame::ID_VIEW_LIVE,				IDH_Views_Live_View},

// bar IDs
{ID_BAR_Properties,						IDH_Docking_Windows_Properties_bar},
{ID_BAR_Channels,						IDH_Docking_Windows_Channels_bar},
{ID_BAR_Presets,						IDH_Docking_Windows_Presets_bar},
{ID_BAR_Parts,							IDH_Docking_Windows_Parts_bar},
{ID_BAR_Modulations,					IDH_Docking_Windows_Modulations_bar},
{ID_BAR_MidiInput,						IDH_Docking_Windows_MIDI_Input_bar},
{ID_BAR_MidiOutput,						IDH_Docking_Windows_MIDI_Output_bar},
{ID_BAR_Piano,							IDH_Docking_Windows_Piano_bar},
{ID_BAR_Graph,							IDH_Docking_Windows_Graph_bar},
{ID_BAR_Phase,							IDH_Docking_Windows_Phase_bar},
{ID_BAR_StepValues,						IDH_Docking_Windows_Step_Values_bar},
{ID_BAR_Mapping,						IDH_Docking_Windows_Mapping_bar},

// standard command IDs
{ID_APP_ABOUT,							IDH_Menus_Help_About},
{ID_APP_EXIT,							IDH_Menus_File_Exit},
{ID_EDIT_COPY,							IDH_Menus_Edit_Copy},
{ID_EDIT_CUT,							IDH_Menus_Edit_Cut},
{ID_EDIT_FIND,							IDH_Menus_Edit_Find},
{ID_EDIT_REDO,							IDH_Menus_Edit_Redo},
{ID_EDIT_PASTE,							IDH_Menus_Edit_Paste},
{ID_EDIT_REPLACE,						IDH_Menus_Edit_Replace},
{ID_EDIT_SELECT_ALL,					IDH_Menus_Edit_Select_All},
{ID_EDIT_UNDO,							IDH_Menus_Edit_Undo},
{ID_FILE_CLOSE,							IDH_Menus_File_Close},
{ID_FILE_NEW,							IDH_Menus_File_New},
{ID_FILE_OPEN,							IDH_Menus_File_Open},
{ID_FILE_SAVE,							IDH_Menus_File_Save},
{ID_FILE_SAVE_AS,						IDH_Menus_File_Save_As},
{ID_HELP_FINDER,						IDH_Menus_Help_Help_Topics},
{ID_VIEW_TOOLBAR,						IDH_Docking_Windows_Toolbar},
{ID_VIEW_STATUS_BAR,					IDH_Menus_View_Status_Bar}, 
{ID_WINDOW_NEW, 						IDH_Menus_Window_New_Window},

// custom command IDs
{ID_APP_CHECK_FOR_UPDATES,				IDH_Menus_Help_Check_for_Updates},
{ID_APP_HOME_PAGE,						IDH_Menus_Help_Polymeter_on_the_Web},
{ID_EDIT_DELETE,						IDH_Menus_Edit_Delete},
{ID_EDIT_DESELECT,						IDH_Menus_Edit_Deselect},
{ID_EDIT_INSERT,						IDH_Menus_Edit_Insert},
{ID_EDIT_RENAME,						IDH_Menus_Edit_Rename},
{ID_FILE_EXPORT,						IDH_Menus_File_Export},
{ID_FILE_IMPORT,						IDH_Menus_File_Import},
{ID_GRAPH_EDGE_LABELS,					IDH_Docking_Windows_Graph_bar_Graph_context_menu},
{ID_GRAPH_HIGHLIGHT_SELECT, 			IDH_Docking_Windows_Graph_bar_Graph_context_menu},
{ID_GRAPH_RELOAD,						IDH_Docking_Windows_Graph_bar_Graph_context_menu},
{ID_GRAPH_SAVEAS,						IDH_Docking_Windows_Graph_bar_Graph_context_menu},
{ID_GRAPH_ZOOM_IN,						IDH_Docking_Windows_Graph_bar_Graph_context_menu},
{ID_GRAPH_ZOOM_OUT, 					IDH_Docking_Windows_Graph_bar_Graph_context_menu},
{ID_GRAPH_ZOOM_RESET,					IDH_Docking_Windows_Graph_bar_Graph_context_menu},
{ID_INDICATOR_SONG_POS,					0},
{ID_INDICATOR_SONG_TIME,				0},
{ID_LIST_COL_HDR_RESET, 				0},
{ID_MAPPING_MAP_SELECTED_TRACKS,		IDH_Docking_Windows_Mapping_bar_Mapping_context_menu},
{ID_MIDI_EVENT_CLEAR_HISTORY,			IDH_Docking_Windows_MIDI_Input_bar_MIDI_IO_context_menu},
{ID_MIDI_EVENT_EXPORT,					IDH_Docking_Windows_MIDI_Input_bar_MIDI_IO_context_menu},
{ID_MIDI_EVENT_PAUSE,					IDH_Docking_Windows_MIDI_Input_bar_MIDI_IO_context_menu},
{ID_MIDI_EVENT_RESET_FILTERS,			IDH_Docking_Windows_MIDI_Input_bar_MIDI_IO_context_menu},
{ID_MIDI_EVENT_SHOW_CONTROLLER_NAMES,	IDH_Docking_Windows_MIDI_Input_bar_MIDI_IO_context_menu},
{ID_MIDI_EVENT_SHOW_NOTE_NAMES, 		IDH_Docking_Windows_MIDI_Input_bar_MIDI_IO_context_menu},
{ID_MIDI_EVENT_SHOW_SYSTEM_MESSAGES,	IDH_Docking_Windows_MIDI_Input_bar_MIDI_IO_context_menu},
{ID_MODULATION_INSERT_GROUP,			0},
{ID_MODULATION_SHOW_DIFFERENCES,		0},
{ID_MODULATION_SORT_BY_SOURCE,			0},
{ID_MODULATION_SORT_BY_TYPE,			0},
{ID_PARTS_SELECT_TRACKS,				0},
{ID_PARTS_SORT_BY_NAME,					0},
{ID_PARTS_SORT_BY_TRACK,				0},
{ID_PHASE_EXPORT_VIDEO, 				0},
{ID_PIANO_COLOR_VELOCITY,				IDH_Docking_Windows_Piano_bar_Piano_context_menu},
{ID_PIANO_INSERT_TRACK, 				IDH_Docking_Windows_Piano_bar_Piano_context_menu},
{ID_PIANO_ROTATE_LABELS,				IDH_Docking_Windows_Piano_bar_Piano_context_menu},
{ID_PIANO_SHOW_KEY_LABELS,				IDH_Docking_Windows_Piano_bar_Piano_context_menu},
{ID_STEP_VALUES_DELIMIT_COMMA,			0},
{ID_STEP_VALUES_DELIMIT_TAB,			0},
{ID_STEP_VALUES_EXPORT_COPY,			0},
{ID_STEP_VALUES_FORMAT_HEX, 			0},
{ID_STEP_VALUES_FORMAT_NOTES,			0},
{ID_STEP_VALUES_FORMAT_OCTAVES, 		0},
{ID_STEP_VALUES_FORMAT_SIGNED,			0},
{ID_STEP_VALUES_FORMAT_TIES,			0},
{ID_STEP_VALUES_LAYOUT_COLS_STEPS,		0},
{ID_STEP_VALUES_LAYOUT_COLS_TRACKS, 	0},
{ID_TOOLS_CONVERGENCES, 				IDH_Menus_Tools_Convergences_Calculator},
{ID_TOOLS_DEVICES,						IDH_Menus_Tools_Devices},
{ID_TOOLS_EXPORT_MODULATIONS,			IDH_Menus_Tools_Export_Table_Export_Modulations},
{ID_TOOLS_EXPORT_SONG,					IDH_Menus_Tools_Export_Table_Export_Song},
{ID_TOOLS_EXPORT_STEPS, 				IDH_Menus_Tools_Export_Table_Export_Steps},
{ID_TOOLS_EXPORT_TRACKS,				IDH_Menus_Tools_Export_Table_Export_Tracks},
{ID_TOOLS_IMPORT_MODULATIONS,			IDH_Menus_Tools_Import_Table_Import_Modulations},
{ID_TOOLS_IMPORT_STEPS, 				IDH_Menus_Tools_Import_Table_Import_Steps},
{ID_TOOLS_IMPORT_TRACKS,				IDH_Menus_Tools_Import_Table_Import_Tracks},
{ID_TOOLS_MIDI_LEARN,					IDH_Menus_Tools_MIDI_Learn},
{ID_TOOLS_OPTIONS,						IDH_Menus_Tools_Options},
{ID_TOOLS_PRIME_FACTORS,				IDH_Menus_Tools_Prime_Factors},
{ID_TOOLS_STATISTICS,					IDH_Menus_Tools_Statistics},
{ID_TOOLS_TIME_TO_REPEAT,				IDH_Menus_Tools_Time_To_Repeat},
{ID_TOOLS_VELOCITY_RANGE,				IDH_Menus_Tools_Velocity_Range},
{ID_TRACK_COLOR,						IDH_Menus_Track_Color},
{ID_TRACK_FILL, 						IDH_Menus_Track_Fill},
{ID_TRACK_GROUP,						IDH_Menus_Track_Create_Group},
{ID_TRACK_INVERT,						IDH_Menus_Track_Invert},
{ID_TRACK_LENGTH,						IDH_Menus_Track_Length},
{ID_TRACK_MODULATION,					IDH_Menus_Track_Create_Modulation},
{ID_TRACK_MUTE, 						IDH_Menus_Track_Mute},
{ID_TRACK_OFFSET,						IDH_Menus_Track_Rotate_Offset_Tracks},
{ID_TRACK_PART_CREATE,					0},
{ID_TRACK_PART_UPDATE,					0},
{ID_TRACK_PRESET_APPLY, 				0},
{ID_TRACK_PRESET_CREATE,				IDH_Menus_Track_Create_Preset},
{ID_TRACK_PRESET_UPDATE,				0},
{ID_TRACK_REVERSE,						IDH_Menus_Track_Reverse},
{ID_TRACK_ROTATE_LEFT,					IDH_Menus_Track_Rotate_Rotate_Left},
{ID_TRACK_ROTATE_RIGHT, 				IDH_Menus_Track_Rotate_Rotate_Right},
{ID_TRACK_ROTATE_STEPS, 				IDH_Menus_Track_Rotate_Rotate_Steps},
{ID_TRACK_SHIFT_LEFT,					IDH_Menus_Track_Shift_Shift_Left},
{ID_TRACK_SHIFT_RIGHT,					IDH_Menus_Track_Shift_Shift_Right},
{ID_TRACK_SHIFT_STEPS,					IDH_Menus_Track_Shift_Shift_Steps},
{ID_TRACK_SOLO, 						IDH_Menus_Track_Solo},
{ID_TRACK_SORT, 						IDH_Menus_Track_Sort},
{ID_TRACK_STRETCH,						IDH_Menus_Track_Stretch},
{ID_TRACK_TIE_NOTES,					IDH_Menus_Track_Tie_Notes},
{ID_TRACK_TRANSPOSE,					IDH_Menus_Track_Transpose},
{ID_TRACK_VELOCITY, 					IDH_Menus_Track_Velocity},
{ID_TRANSPORT_CONVERGENCE_NEXT, 		IDH_Menus_Transport_Next_Convergence},
{ID_TRANSPORT_CONVERGENCE_PREVIOUS, 	IDH_Menus_Transport_Previous_Convergence},
{ID_TRANSPORT_CONVERGENCE_SIZE_ALL, 	IDH_Menus_Transport_Convergence_Size},
{ID_TRANSPORT_CONVERGENCE_SIZE_CUSTOM, 	IDH_Menus_Transport_Convergence_Size},
{ID_TRANSPORT_GO_TO_POSITION,			IDH_Menus_Transport_Go_To_Position},
{ID_TRANSPORT_LOOP,						IDH_Menus_Transport_Loop},
{ID_TRANSPORT_PAUSE,					IDH_Menus_Transport_Pause},
{ID_TRANSPORT_PLAY, 					IDH_Menus_Transport_Play},
{ID_TRANSPORT_RECORD,					IDH_Menus_Transport_Record},
{ID_TRANSPORT_RECORD_TRACKS,			IDH_Menus_Transport_Record_Tracks},
{ID_TRANSPORT_REWIND,					IDH_Menus_Transport_Rewind},
{ID_VIEW_APPLOOK_OFF_2003,				IDH_Menus_View_Application_Look},
{ID_VIEW_APPLOOK_OFF_2007_AQUA, 		IDH_Menus_View_Application_Look},
{ID_VIEW_APPLOOK_OFF_2007_BLACK,		IDH_Menus_View_Application_Look},
{ID_VIEW_APPLOOK_OFF_2007_BLUE, 		IDH_Menus_View_Application_Look},
{ID_VIEW_APPLOOK_OFF_2007_SILVER,		IDH_Menus_View_Application_Look},
{ID_VIEW_APPLOOK_OFF_XP,				IDH_Menus_View_Application_Look},
{ID_VIEW_APPLOOK_VS_2005,				IDH_Menus_View_Application_Look},
{ID_VIEW_APPLOOK_VS_2008,				IDH_Menus_View_Application_Look},
{ID_VIEW_APPLOOK_WINDOWS_7, 			IDH_Menus_View_Application_Look},
{ID_VIEW_APPLOOK_WIN_2000,				IDH_Menus_View_Application_Look},
{ID_VIEW_APPLOOK_WIN_XP,				IDH_Menus_View_Application_Look},
{ID_VIEW_CHANNELS,						IDH_Menus_View_Show_Channels},
{ID_VIEW_CUSTOMIZE, 					0},
{ID_VIEW_MODULATIONS,					IDH_Menus_View_Show_Modulations},
{ID_VIEW_PARTS, 						IDH_Menus_View_Groups_Show_Parts},
{ID_VIEW_PRESETS,						IDH_Menus_View_Groups_Show_Presets},
{ID_VIEW_PROPERTIES,					IDH_Menus_View_Show_Properties},
{ID_VIEW_TYPE_LIVE, 					IDH_Menus_View_Show_Live_View},
{ID_VIEW_TYPE_SONG, 					IDH_Menus_View_Show_Song_View},
{ID_VIEW_TYPE_TRACK,					IDH_Menus_View_Show_Track_View},
{ID_VIEW_VELOCITIES,					IDH_Menus_View_Show_Velocities},
{ID_VIEW_ZOOM_IN,						IDH_Menus_View_Zoom_In},
{ID_VIEW_ZOOM_OUT,						IDH_Menus_View_Zoom_Out},
{ID_VIEW_ZOOM_RESET,					IDH_Menus_View_Zoom_Reset},
{ID_WINDOW_FULL_SCREEN, 				IDH_Menus_Window_Full_Screen},
{ID_WINDOW_MANAGER, 					IDH_Menus_Window_Windows},
{ID_WINDOW_NEW_HORZ_TAB_GROUP,			IDH_Menus_Window_New_Horizontal_Tab_Group},
{ID_WINDOW_NEW_VERT_TAB_GROUP,			IDH_Menus_Window_New_Vertical_Tab_Group},
{ID_WINDOW_RESET_LAYOUT,				IDH_Menus_Window_Reset_Layout},

// dialog IDs
{IDD_ABOUTBOX,							IDH_Menus_Help_About},
{IDD_CONVERGENCES,						IDH_Menus_Tools_Convergences_Calculator},
{IDD_EXPORT,							IDH_Menus_File_Export},
{IDD_FILL,								IDH_Menus_Track_Fill},
{IDD_GO_TO_POSITION,					IDH_Menus_Transport_Go_To_Position},
{IDD_MODULATION,						IDH_Menus_Track_Create_Modulation},
{IDD_OFFSET,							IDH_Menus_Track_Rotate_Offset_Tracks},
{IDD_OPTIONS,							IDH_Menus_Tools_Options},
{IDD_PROCESSING,						0},
{IDD_PROGRESS,							0},
{IDD_RECORD,							IDH_Menus_Transport_Record},
{IDD_STRETCH,							IDH_Menus_Track_Stretch},
{IDD_TRACK_SORT,						IDH_Menus_Track_Sort},
{IDD_VELOCITY_OFFSET,					IDH_Menus_Track_Velocity},
{IDD_VELOCITY_SCALE,					IDH_Menus_Track_Velocity},

// string IDs
{IDS_OPT_NAME_General_bAlwaysRecord,	IDH_Options_General_Always_Record},
{IDS_OPT_NAME_General_bCheckForUpdates,	IDH_Options_General_Automatically_Check_for_Updates},
{IDS_OPT_NAME_General_bPropertyDescrips,	IDH_Options_General_Show_Property_Descriptions},
{IDS_OPT_NAME_Midi_bSendMidiClock,		IDH_Options_MIDI_Send_MIDI_Clock},
{IDS_OPT_NAME_Midi_bThru,				IDH_Options_MIDI_Thru},
{IDS_OPT_NAME_Midi_iInputDevice,		IDH_Options_MIDI_Input_Device},
{IDS_OPT_NAME_Midi_iInputQuant,			IDH_Options_MIDI_Input_Quantization},
{IDS_OPT_NAME_Midi_iOutputDevice,		IDH_Options_MIDI_Output_Device},
{IDS_OPT_NAME_Midi_nBufferSize,			IDH_Options_MIDI_Buffer_Size},
{IDS_OPT_NAME_Midi_nDefaultVelocity,	IDH_Options_MIDI_Default_Velocity},
{IDS_OPT_NAME_Midi_nLatency,			IDH_Options_MIDI_Latency},
{IDS_OPT_NAME_Midi_nRecordInput,		IDH_Options_MIDI_Record_Input},
{IDS_OPT_NAME_View_bShowCurPos,			IDH_Options_View_Show_Current_Position},
{IDS_OPT_NAME_View_bShowGMNames,		IDH_Options_View_Show_General_MIDI_Names},
{IDS_OPT_NAME_View_bShowNoteNames,		IDH_Options_View_Show_Note_Names},
{IDS_OPT_NAME_View_bShowTrackColors,	IDH_Options_View_Show_Track_Colors},
{IDS_OPT_NAME_View_bUniqueTrackNames,	IDH_Options_View_Unique_Track_Names},
{IDS_OPT_NAME_View_fUpdateFreq,			IDH_Options_View_Update_Frequency},
{IDS_OPT_NAME_View_fZoomDelta,			IDH_Options_View_Zoom_Step},
{IDS_OPT_NAME_View_nLiveFontHeight,		IDH_Options_View_Live_View_Font_Height},
{IDS_PDR_NAME_fTempo,					IDH_Properties_Tempo},
{IDS_PDR_NAME_iNoteOverlap,				IDH_Properties_Note_Overlap},
{IDS_PDR_NAME_nKeySig,					IDH_Properties_Key_Signature},
{IDS_PDR_NAME_nLoopFrom,				IDH_Properties_Loop_From},
{IDS_PDR_NAME_nLoopTo,					IDH_Properties_Loop_To},
{IDS_PDR_NAME_nMeter,					IDH_Properties_Meter},
{IDS_PDR_NAME_nRecordOffset,			IDH_Properties_Record_Offset},
{IDS_PDR_NAME_nSongLength,				IDH_Properties_Song_Length},
{IDS_PDR_NAME_nStartPos,				IDH_Properties_Start_Position},
{IDS_PDR_NAME_nTimeDiv,					IDH_Properties_Timebase},

// handle dynamically generated submenus
{IDS_HINT_GRAPH_LAYOUT,					IDH_Docking_Windows_Graph_bar_Graph_context_menu},
{IDS_HINT_GRAPH_SCOPE_ALL,				IDH_Docking_Windows_Graph_bar_Graph_context_menu},
{IDS_HINT_GRAPH_SCOPE_SELECTED,			IDH_Docking_Windows_Graph_bar_Graph_context_menu},
{IDS_HINT_GRAPH_SCOPE_RECURSIVE,		IDH_Docking_Windows_Graph_bar_Graph_context_menu},
{IDS_HINT_GRAPH_SCOPE_BIDIRECTIONAL,	IDH_Docking_Windows_Graph_bar_Graph_context_menu},
{IDS_HINT_GRAPH_FILTER_MOD_TYPE_ALL,	IDH_Docking_Windows_Graph_bar_Graph_context_menu},
{IDS_HINT_GRAPH_FILTER_MOD_TYPE,		IDH_Docking_Windows_Graph_bar_Graph_context_menu},
{IDS_HINT_MAIN_CONVERGENCE_SIZE,		IDH_Menus_Transport_Convergence_Size},
{IDS_HINT_PIANO_FILTER_CHANNEL,			IDH_Docking_Windows_Piano_bar_Piano_context_menu},
{IDS_SM_FILTER_CHANNEL_ALL,				IDH_Docking_Windows_MIDI_Input_bar_MIDI_IO_context_menu},
{IDS_SM_FILTER_CHANNEL_SELECT,			IDH_Docking_Windows_MIDI_Input_bar_MIDI_IO_context_menu},
{IDS_SM_FILTER_MESSAGE_ALL,				IDH_Docking_Windows_MIDI_Input_bar_MIDI_IO_context_menu},
{IDS_SM_FILTER_MESSAGE_SELECT,			IDH_Docking_Windows_MIDI_Input_bar_MIDI_IO_context_menu},
{IDS_SM_OUTPUT_CHANNEL_NONE,			IDH_Docking_Windows_Piano_bar_Piano_context_menu},
{IDS_SM_OUTPUT_CHANNEL_SELECT,			IDH_Docking_Windows_Piano_bar_Piano_context_menu},
{IDS_SM_PIANO_SIZE,						IDH_Docking_Windows_Graph_bar_Graph_context_menu},

// handle use of COffsetDlg by multiple commands
{IDS_EDIT_ROTATE,						IDH_Menus_Track_Rotate_Rotate_Steps},
{IDS_EDIT_SHIFT,						IDH_Menus_Track_Shift_Shift_Steps},
{IDS_TRK_Offset,						IDH_Menus_Track_Rotate_Offset_Tracks},
{IDS_EDIT_TRANSPOSE,					IDH_Menus_Track_Transpose},
{IDS_CONVERGENCE_SIZE,					IDH_Menus_Transport_Convergence_Size},
