//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Polymeter.rc
//
#define IDR_MAINFRAME                   101
#define IDR_GRAPH_CTX                   102
#define IDR_LIST_COL_HDR                103
#define IDR_MAINFRAME_256               104
#define IDR_MAPPING_CTX                 105
#define IDR_MIDI_EVENT_CTX              106
#define IDR_MODULATION_CTX              107
#define IDR_PARTS_CTX                   108
#define IDR_PHASE_CTX                   109
#define IDR_PIANO_CTX                   110
#define IDR_POPUP_EDIT                  111
#define IDR_PRESETS_CTX                 112
#define IDR_PolymeterTYPE               113
#define IDR_STEP_VALUES_CTX             114
#define IDR_THEME_MENU                  115
#define IDR_VIEW_EX_CTX                 116
#define IDB_FILTER                      117
#define IDD_ABOUTBOX                    118
#define IDD_CONVERGENCES                119
#define IDD_EXPORT                      120
#define IDD_FILL                        121
#define IDD_GO_TO_POSITION              122
#define IDD_MODULATION                  123
#define IDD_MODULATION_TYPE             124
#define IDD_OFFSET                      125
#define IDD_OPTIONS                     126
#define IDD_PROCESSING                  127
#define IDD_PROGRESS                    128
#define IDD_RECORD                      129
#define IDD_STRETCH                     130
#define IDD_TRACK_SORT                  131
#define IDD_VELOCITY_OFFSET             132
#define IDD_VELOCITY_REPLACE            133
#define IDD_VELOCITY_SCALE              134
#define IDS_APP_HELP_FILE_MISSING       200
#define IDS_APP_LICENSE                 201
#define IDS_APP_UNKNOWN_SYSTEM_ERROR    202
#define IDS_BAR_Channels                203
#define IDS_BAR_Graph                   204
#define IDS_BAR_Mapping                 205
#define IDS_BAR_MidiInput               206
#define IDS_BAR_MidiOutput              207
#define IDS_BAR_Modulations             208
#define IDS_BAR_Parts                   209
#define IDS_BAR_Phase                   210
#define IDS_BAR_Piano                   211
#define IDS_BAR_Presets                 212
#define IDS_BAR_Properties              213
#define IDS_BAR_StepValues              214
#define IDS_CHANNEL_COL_BankLSB         215
#define IDS_CHANNEL_COL_BankMSB         216
#define IDS_CHANNEL_COL_Number          217
#define IDS_CHANNEL_COL_Overlaps        218
#define IDS_CHANNEL_COL_Pan             219
#define IDS_CHANNEL_COL_Patch           220
#define IDS_CHANNEL_COL_Volume          221
#define IDS_CHAN_NOTE_OVERLAP_MERGE     222
#define IDS_CHAN_NOTE_OVERLAP_SPLIT     223
#define IDS_CHECK_MODULATIONS_ERRORS    224
#define IDS_CHECK_MODULATIONS_SUCCESS   225
#define IDS_CKUP_CANT_GET_ADDR          226
#define IDS_CKUP_CANT_LOAD_DLL          227
#define IDS_COLOR_MENU_AUTOMATIC        228
#define IDS_COLOR_MENU_MORE_COLORS      229
#define IDS_CONVERGENCE_SIZE            230
#define IDS_CONVERGENCE_SIZE_EDIT_CAPTION 231
#define IDS_CONVERGE_HINT               232
#define IDS_CSV_FILE_FILTER             233
#define IDS_DOC_BAD_FORMAT              234
#define IDS_DOC_BAD_STEP_SELECTION      235
#define IDS_DOC_CANT_TRUNCATE_RECORDING 236
#define IDS_DOC_CLIP_WARNING            237
#define IDS_DOC_CONVERGENCE_OUT_OF_RANGE 238
#define IDS_DOC_GROUP_OVERLAP           239
#define IDS_DOC_NEWER_VERSION           240
#define IDS_DOC_SEARCH_TEXT_NOT_FOUND   241
#define IDS_DOC_TRACK_TOO_LONG          242
#define IDS_DOC_VALUE_NOT_FOUND         243
#define IDS_DOC_VELOCITY_RANGE          244
#define IDS_EDIT_APPLY_PRESET           245
#define IDS_EDIT_CREATE_PART            246
#define IDS_EDIT_CREATE_PRESET          247
#define IDS_EDIT_CUT_MAPPINGS           248
#define IDS_EDIT_CUT_STEPS              249
#define IDS_EDIT_CUT_TRACKS             250
#define IDS_EDIT_DELETE_MAPPINGS        251
#define IDS_EDIT_DELETE_PARTS           252
#define IDS_EDIT_DELETE_PRESETS         253
#define IDS_EDIT_DELETE_STEPS           254
#define IDS_EDIT_DELETE_TRACKS          255
#define IDS_EDIT_DUB                    256
#define IDS_EDIT_FILL_STEPS             257
#define IDS_EDIT_INSERT_MAPPING         258
#define IDS_EDIT_INSERT_STEPS           259
#define IDS_EDIT_INSERT_TRACKS          260
#define IDS_EDIT_INVERT                 261
#define IDS_EDIT_LEARN_MAPPING          262
#define IDS_EDIT_LEARN_MULTI_MAPPING    263
#define IDS_EDIT_LOOP_RANGE             264
#define IDS_EDIT_MENU                   265
#define IDS_EDIT_MODIFY_PARTS           266
#define IDS_EDIT_MODULATION             267
#define IDS_EDIT_MOVE_MAPPINGS          268
#define IDS_EDIT_MOVE_PARTS             269
#define IDS_EDIT_MOVE_PRESETS           270
#define IDS_EDIT_MOVE_STEPS             271
#define IDS_EDIT_MOVE_TRACKS            272
#define IDS_EDIT_MULTI_STEP_RECT        273
#define IDS_EDIT_PASTE_MAPPINGS         274
#define IDS_EDIT_PASTE_STEPS            275
#define IDS_EDIT_PASTE_TRACKS           276
#define IDS_EDIT_RECORD                 277
#define IDS_EDIT_REDO_PREFIX            278
#define IDS_EDIT_RENAME_PART            279
#define IDS_EDIT_RENAME_PRESET          280
#define IDS_EDIT_REVERSE                281
#define IDS_EDIT_ROTATE                 282
#define IDS_EDIT_SHIFT                  283
#define IDS_EDIT_SOLO                   284
#define IDS_EDIT_SORT_MAPPINGS          285
#define IDS_EDIT_SORT_PARTS             286
#define IDS_EDIT_TIME_DIVISION          287
#define IDS_EDIT_TRACK_SORT             288
#define IDS_EDIT_TRANSPOSE              289
#define IDS_EDIT_UNDO_PREFIX            290
#define IDS_EDIT_UPDATE_PART            291
#define IDS_EDIT_UPDATE_PRESET          292
#define IDS_EDIT_VELOCITY               293
#define IDS_ERR_TRACK_LENGTH_CURSOR     294
#define IDS_EXPORT                      295
#define IDS_EXPORT_BAD_DURATION         296
#define IDS_EXPORT_EMPTY_FILE           297
#define IDS_EXPORT_ERROR                298
#define IDS_EXPORT_FILE_FILTER          299
#define IDS_EXPORT_MODULATIONS          300
#define IDS_EXPORT_SONG                 301
#define IDS_EXPORT_STEPS                302
#define IDS_EXPORT_TRACKS               303
#define IDS_FILTER_ALL                  304
#define IDS_GRAPHVIZ_BROWSE_TITLE       305
#define IDS_GRAPHVIZ_DOWNLOAD_IT        306
#define IDS_GRAPHVIZ_IS_IT_PRESENT      307
#define IDS_GRAPHVIZ_IS_LOCATION_KNOWN  308
#define IDS_GRAPHVIZ_IS_READY           309
#define IDS_GRAPHVIZ_NOT_FOUND_RETRY    310
#define IDS_GRAPHVIZ_OK_TO_SEARCH       311
#define IDS_GRAPHVIZ_SEARCHING_DRIVE    312
#define IDS_GRAPH_ERROR                 313
#define IDS_GRAPH_FILTER_MULTI          314
#define IDS_GRAPH_SCOPE_ALL             315
#define IDS_GRAPH_SCOPE_BIDIRECTIONAL   316
#define IDS_GRAPH_SCOPE_SOURCES         317
#define IDS_GRAPH_SCOPE_TARGETS         318
#define IDS_GRID_ERR_BAD_TIME_FORMAT    319
#define IDS_HINT_APPLOOK_SELECT         320
#define IDS_HINT_GRAPH_DEPTH            321
#define IDS_HINT_GRAPH_DEPTH_MAX        322
#define IDS_HINT_GRAPH_FILTER_MOD_TYPE  323
#define IDS_HINT_GRAPH_FILTER_MOD_TYPE_ALL 324
#define IDS_HINT_GRAPH_FILTER_MOD_TYPE_MULTI 325
#define IDS_HINT_GRAPH_LAYOUT           326
#define IDS_HINT_GRAPH_SCOPE_ALL        327
#define IDS_HINT_GRAPH_SCOPE_BIDIRECTIONAL 328
#define IDS_HINT_GRAPH_SCOPE_SOURCES    329
#define IDS_HINT_GRAPH_SCOPE_TARGETS    330
#define IDS_HINT_MAIN_CONVERGENCE_SIZE  331
#define IDS_HLINK_CANT_LAUNCH           332
#define IDS_IMPORT                      333
#define IDS_IMPORT_ERR_FORMAT           334
#define IDS_IMPORT_ERR_LOCATION         335
#define IDS_IMPORT_ERR_PROPERTY         336
#define IDS_IMPORT_ERR_RANGE            337
#define IDS_IMPORT_MODULATIONS          338
#define IDS_IMPORT_STEPS                339
#define IDS_IMPORT_TRACKS               340
#define IDS_MAIN_DOCKING_BAR_HINT_FMT   341
#define IDS_MAIN_TRACK_COLORS           342
#define IDS_MAPPING_COL_IN_CHANNEL      343
#define IDS_MAPPING_COL_IN_CONTROL      344
#define IDS_MAPPING_COL_IN_EVENT        345
#define IDS_MAPPING_COL_NUMBER          346
#define IDS_MAPPING_COL_OUT_CHANNEL     347
#define IDS_MAPPING_COL_OUT_CONTROL     348
#define IDS_MAPPING_COL_OUT_EVENT       349
#define IDS_MAPPING_COL_RANGE_END       350
#define IDS_MAPPING_COL_RANGE_START     351
#define IDS_MAPPING_COL_TRACK           352
#define IDS_MIDIEVT_COL_CHANNEL         353
#define IDS_MIDIEVT_COL_MESSAGE         354
#define IDS_MIDIEVT_COL_P1              355
#define IDS_MIDIEVT_COL_P2              356
#define IDS_MIDIEVT_COL_TIME            357
#define IDS_MIDI_DEVICES_MISSING        358
#define IDS_MIDI_INCOMPATIBLE_SONG_POSITION 359
#define IDS_MIDI_INPUT                  360
#define IDS_MIDI_MSG_NOTE_OFF           361
#define IDS_MIDI_MSG_NOTE_ON            362
#define IDS_MIDI_NO_OUTPUT_DEVICE       363
#define IDS_MIDI_OUTPUT                 364
#define IDS_MIDI_SYS_STAT_ACTIVE_SENSING 365
#define IDS_MIDI_SYS_STAT_CLOCK         366
#define IDS_MIDI_SYS_STAT_CONTINUE      367
#define IDS_MIDI_SYS_STAT_EOX           368
#define IDS_MIDI_SYS_STAT_MTC_QTR_FRAME 369
#define IDS_MIDI_SYS_STAT_SONG_POSITION 370
#define IDS_MIDI_SYS_STAT_SONG_SELECT   371
#define IDS_MIDI_SYS_STAT_START         372
#define IDS_MIDI_SYS_STAT_STOP          373
#define IDS_MIDI_SYS_STAT_SYSEX         374
#define IDS_MIDI_SYS_STAT_SYSTEM_RESET  375
#define IDS_MIDI_SYS_STAT_TUNE_REQUEST  376
#define IDS_MODERR_INFINITE_LOOP        377
#define IDS_MODERR_UNSUPPORTED_MOD_TYPE 378
#define IDS_MOD_DIFFERENCES             379
#define IDS_MOD_SOURCE                  380
#define IDS_NONE                        381
#define IDS_NOTE_OVERLAP_Allow          382
#define IDS_NOTE_OVERLAP_Prevent        383
#define IDS_OFFSET_NOTES                384
#define IDS_OFFSET_STEPS                385
#define IDS_OFFSET_TICKS                386
#define IDS_OPT_DESC_General_bAlwaysRecord 387
#define IDS_OPT_DESC_General_bCheckForUpdates 388
#define IDS_OPT_DESC_General_bPropertyDescrips 389
#define IDS_OPT_DESC_Midi_bSendMidiClock 390
#define IDS_OPT_DESC_Midi_bThru         391
#define IDS_OPT_DESC_Midi_iInputDevice  392
#define IDS_OPT_DESC_Midi_iInputQuant   393
#define IDS_OPT_DESC_Midi_iOutputDevice 394
#define IDS_OPT_DESC_Midi_nBufferSize   395
#define IDS_OPT_DESC_Midi_nDefaultVelocity 396
#define IDS_OPT_DESC_Midi_nLatency      397
#define IDS_OPT_DESC_Midi_nRecordInput  398
#define IDS_OPT_DESC_View_bShowCurPos   399
#define IDS_OPT_DESC_View_bShowGMNames  400
#define IDS_OPT_DESC_View_bShowNoteNames 401
#define IDS_OPT_DESC_View_bShowTrackColors 402
#define IDS_OPT_DESC_View_bUniqueTrackNames 403
#define IDS_OPT_DESC_View_fUpdateFreq   404
#define IDS_OPT_DESC_View_fZoomDelta    405
#define IDS_OPT_DESC_View_nLiveFontHeight 406
#define IDS_OPT_GROUP_General           407
#define IDS_OPT_GROUP_Midi              408
#define IDS_OPT_GROUP_View              409
#define IDS_OPT_NAME_General_bAlwaysRecord 410
#define IDS_OPT_NAME_General_bCheckForUpdates 411
#define IDS_OPT_NAME_General_bPropertyDescrips 412
#define IDS_OPT_NAME_Midi_bSendMidiClock 413
#define IDS_OPT_NAME_Midi_bThru         414
#define IDS_OPT_NAME_Midi_iInputDevice  415
#define IDS_OPT_NAME_Midi_iInputQuant   416
#define IDS_OPT_NAME_Midi_iOutputDevice 417
#define IDS_OPT_NAME_Midi_nBufferSize   418
#define IDS_OPT_NAME_Midi_nDefaultVelocity 419
#define IDS_OPT_NAME_Midi_nLatency      420
#define IDS_OPT_NAME_Midi_nRecordInput  421
#define IDS_OPT_NAME_View_bShowCurPos   422
#define IDS_OPT_NAME_View_bShowGMNames  423
#define IDS_OPT_NAME_View_bShowNoteNames 424
#define IDS_OPT_NAME_View_bShowTrackColors 425
#define IDS_OPT_NAME_View_bUniqueTrackNames 426
#define IDS_OPT_NAME_View_fUpdateFreq   427
#define IDS_OPT_NAME_View_fZoomDelta    428
#define IDS_OPT_NAME_View_nLiveFontHeight 429
#define IDS_PDR_DESC_fTempo             430
#define IDS_PDR_DESC_iNoteOverlap       431
#define IDS_PDR_DESC_nKeySig            432
#define IDS_PDR_DESC_nLoopFrom          433
#define IDS_PDR_DESC_nLoopTo            434
#define IDS_PDR_DESC_nMeter             435
#define IDS_PDR_DESC_nRecordOffset      436
#define IDS_PDR_DESC_nSongLength        437
#define IDS_PDR_DESC_nStartPos          438
#define IDS_PDR_DESC_nTimeDiv           439
#define IDS_PDR_GROUP_Master            440
#define IDS_PDR_NAME_fTempo             441
#define IDS_PDR_NAME_iNoteOverlap       442
#define IDS_PDR_NAME_nKeySig            443
#define IDS_PDR_NAME_nLoopFrom          444
#define IDS_PDR_NAME_nLoopTo            445
#define IDS_PDR_NAME_nMeter             446
#define IDS_PDR_NAME_nRecordOffset      447
#define IDS_PDR_NAME_nSongLength        448
#define IDS_PDR_NAME_nStartPos          449
#define IDS_PDR_NAME_nTimeDiv           450
#define IDS_PHASE_EXPORT_OVERWRITE_WARN 451
#define IDS_PROPS_MORE_COLORS           452
#define IDS_RANGE_TYPE_DUAL             453
#define IDS_RANGE_TYPE_NONE             454
#define IDS_RANGE_TYPE_OCTAVE           455
#define IDS_RECDLG_CUSTOM               456
#define IDS_RECORD_INPUT_OPT_DubsAndMidi 457
#define IDS_RECORD_INPUT_OPT_DubsOnly   458
#define IDS_RECORD_INPUT_OPT_MidiOnly   459
#define IDS_RESET_ALL_OPTIONS           460
#define IDS_SC_MAXIMIZE                 461
#define IDS_SC_RESTORE                  462
#define IDS_SEQERR_BAD_TIME_FORMAT      463
#define IDS_SEQERR_BUFFER_OVERRUN       464
#define IDS_SEQERR_CALLBACK_TOO_LONG    465
#define IDS_SEQERR_TOO_MANY_RECURSIONS  466
#define IDS_SEQ_MIDI_ERROR              467
#define IDS_SM_FILTER_CHANNEL_ALL       468
#define IDS_SM_FILTER_CHANNEL_SELECT    469
#define IDS_SM_FILTER_MESSAGE_ALL       470
#define IDS_SM_FILTER_MESSAGE_SELECT    471
#define IDS_SM_OUTPUT_CHANNEL_NONE      472
#define IDS_SM_OUTPUT_CHANNEL_SELECT    473
#define IDS_SM_PIANO_SIZE               474
#define IDS_SORT_DIR_ASCENDING          475
#define IDS_SORT_DIR_DESCENDING         476
#define IDS_STATUS_PANE1                477
#define IDS_STATUS_PANE2                478
#define IDS_STEP_TIE                    479
#define IDS_SVG_FILE_FILTER             480
#define IDS_TIME_TO_REPEAT_BEATS        481
#define IDS_TIME_TO_REPEAT_DAYS         482
#define IDS_TIME_TO_REPEAT_TICKS        483
#define IDS_TIME_TO_REPEAT_YEARS        484
#define IDS_TOOLBAR_CUSTOMIZE           485
#define IDS_TOOLBAR_STANDARD            486
#define IDS_TRACK_TYPE_CHAN_AFT         487
#define IDS_TRACK_TYPE_CONTROL          488
#define IDS_TRACK_TYPE_KEY_AFT          489
#define IDS_TRACK_TYPE_MODULATOR        490
#define IDS_TRACK_TYPE_NOTE             491
#define IDS_TRACK_TYPE_PATCH            492
#define IDS_TRACK_TYPE_TEMPO            493
#define IDS_TRACK_TYPE_WHEEL            494
#define IDS_TRANSPORT_LOOP              495
#define IDS_TRANSPORT_PAUSE             496
#define IDS_TRANSPORT_PLAY              497
#define IDS_TRANSPORT_RECORD            498
#define IDS_TRK_Channel                 499
#define IDS_TRK_Chord                   500
#define IDS_TRK_Duration                501
#define IDS_TRK_Index                   502
#define IDS_TRK_Length                  503
#define IDS_TRK_Mute                    504
#define IDS_TRK_Name                    505
#define IDS_TRK_Note                    506
#define IDS_TRK_Number                  507
#define IDS_TRK_Offset                  508
#define IDS_TRK_Position                509
#define IDS_TRK_Quant                   510
#define IDS_TRK_Range                   511
#define IDS_TRK_RangeStart              512
#define IDS_TRK_RangeType               513
#define IDS_TRK_STEP                    514
#define IDS_TRK_Scale                   515
#define IDS_TRK_Swing                   516
#define IDS_TRK_Tempo                   517
#define IDS_TRK_Type                    518
#define IDS_TRK_Velocity                519
#define IDS_TRK_Voicing                 520
#define IDS_TYPE_TRACK                  521
#define IDS_VELOCITY                    522
#define IDS_WINDOW_MANAGER              523
#define IDS_WINDOW_RESET_LAYOUT_WARN    524
#define IDP_OLE_INIT_FAILED             525
#define IDC_ABOUT_LICENSE               1001
#define IDC_ABOUT_VERSION               1002
#define IDC_CONVERGE_INPUT              1003
#define IDC_CONVERGE_OUTPUT             1004
#define IDC_CURSOR_DRAG_MULTI           1005
#define IDC_CURSOR_DRAG_SINGLE          1006
#define IDC_EXPORT_DURATION             1007
#define IDC_FILL_CURVINESS              1008
#define IDC_FILL_FREQUENCY              1009
#define IDC_FILL_FUNCTION               1010
#define IDC_FILL_PHASE                  1011
#define IDC_FILL_SIGNED1                1012
#define IDC_FILL_SIGNED2                1013
#define IDC_FILL_STEP_END               1014
#define IDC_FILL_STEP_START             1015
#define IDC_FILL_VALUE_END              1016
#define IDC_FILL_VALUE_START            1017
#define IDC_GO_TO_POS_EDIT              1018
#define IDC_GO_TO_POS_FORMAT_MBT        1019
#define IDC_GO_TO_POS_FORMAT_TIME       1020
#define IDC_MODULATION_SOURCE_LIST      1021
#define IDC_MODULATION_TYPE_LIST        1022
#define IDC_MOD_TYPE_LIST               1023
#define IDC_OFFSET_CAPTION              1024
#define IDC_OFFSET_EDIT                 1025
#define IDC_OFFSET_SPIN                 1026
#define IDC_OPTIONS_GRID                1027
#define IDC_OPTIONS_RESET_ALL           1028
#define IDC_PROCESSING_STATUS           1029
#define IDC_PROGRESS                    1030
#define IDC_PROGRESS_PERCENT            1031
#define IDC_RECORD_DURATION             1032
#define IDC_RECORD_DURATION_UNIT        1033
#define IDC_RECORD_DURATION_UNIT2       1034
#define IDC_RECORD_FRAME_HEIGHT         1035
#define IDC_RECORD_FRAME_HEIGHT_CAP     1036
#define IDC_RECORD_FRAME_RATE           1037
#define IDC_RECORD_FRAME_SIZE           1038
#define IDC_RECORD_FRAME_WIDTH          1039
#define IDC_RECORD_FRAME_WIDTH_CAP      1040
#define IDC_STRETCH_CAPTION             1041
#define IDC_STRETCH_EDIT                1042
#define IDC_STRETCH_INTERPOLATE         1043
#define IDC_TRACK_SORT_DIR1             1044
#define IDC_TRACK_SORT_DIR2             1045
#define IDC_TRACK_SORT_DIR3             1046
#define IDC_TRACK_SORT_PROP1            1047
#define IDC_TRACK_SORT_PROP2            1048
#define IDC_TRACK_SORT_PROP3            1049
#define IDC_VELOCITY_OFFSET_EDIT        1050
#define IDC_VELOCITY_OFFSET_TARGET      1051
#define IDC_VELOCITY_OFFSET_TARGET2     1052
#define IDC_VELOCITY_REPLACE_WHAT       1053
#define IDC_VELOCITY_REPLACE_WITH       1054
#define IDC_VELOCITY_SCALE_EDIT         1055
#define IDC_VELOCITY_SCALE_SIGNED       1056
#define IDC_VELOCITY_SCALE_UNSIGNED     1057
#define ID_APP_CHECK_FOR_UPDATES        32771
#define ID_APP_HOME_PAGE                32772
#define ID_EDIT_DELETE                  32773
#define ID_EDIT_DESELECT                32774
#define ID_EDIT_INSERT                  32775
#define ID_EDIT_RENAME                  32776
#define ID_FILE_EXPORT                  32777
#define ID_FILE_IMPORT                  32778
#define ID_GRAPH_DEPTH_MAX              32779
#define ID_GRAPH_EDGE_LABELS            32780
#define ID_GRAPH_HIGHLIGHT_SELECT       32781
#define ID_GRAPH_LEGEND                 32782
#define ID_GRAPH_RELOAD                 32783
#define ID_GRAPH_SAVEAS                 32784
#define ID_GRAPH_ZOOM_IN                32785
#define ID_GRAPH_ZOOM_OUT               32786
#define ID_GRAPH_ZOOM_RESET             32787
#define ID_INDICATOR_SONG_POS           32788
#define ID_INDICATOR_SONG_TIME          32789
#define ID_INDICATOR_TEMPO              32790
#define ID_LIST_COL_HDR_RESET           32791
#define ID_MAPPING_MAP_SELECTED_TRACKS  32792
#define ID_MIDI_EVENT_CLEAR_HISTORY     32793
#define ID_MIDI_EVENT_EXPORT            32794
#define ID_MIDI_EVENT_PAUSE             32795
#define ID_MIDI_EVENT_RESET_FILTERS     32796
#define ID_MIDI_EVENT_SHOW_CONTROLLER_NAMES 32797
#define ID_MIDI_EVENT_SHOW_NOTE_NAMES   32798
#define ID_MIDI_EVENT_SHOW_SYSTEM_MESSAGES 32799
#define ID_MODULATION_INSERT_GROUP      32800
#define ID_MODULATION_SHOW_DIFFERENCES  32801
#define ID_MODULATION_SORT_BY_SOURCE    32802
#define ID_MODULATION_SORT_BY_TYPE      32803
#define ID_PARTS_SELECT_TRACKS          32804
#define ID_PARTS_SORT_BY_NAME           32805
#define ID_PARTS_SORT_BY_TRACK          32806
#define ID_PHASE_EXPORT_VIDEO           32807
#define ID_PHASE_FULL_SCREEN            32808
#define ID_PHASE_STYLE_00_CIRCULAR_ORBITS 32809
#define ID_PHASE_STYLE_01_3D_PLANETS    32810
#define ID_PHASE_STYLE_02_NIGHT_SKY     32811
#define ID_PHASE_STYLE_03_CROSSHAIRS    32812
#define ID_PHASE_STYLE_04_PERIODS       32813
#define ID_PHASE_STYLE_05_CONVERGENCES  32814
#define ID_PIANO_COLOR_VELOCITY         32815
#define ID_PIANO_INSERT_TRACK           32816
#define ID_PIANO_ROTATE_LABELS          32817
#define ID_PIANO_SHOW_KEY_LABELS        32818
#define ID_STEP_VALUES_DELIMIT_COMMA    32819
#define ID_STEP_VALUES_DELIMIT_TAB      32820
#define ID_STEP_VALUES_EXPORT_COPY      32821
#define ID_STEP_VALUES_FORMAT_HEX       32822
#define ID_STEP_VALUES_FORMAT_NOTES     32823
#define ID_STEP_VALUES_FORMAT_OCTAVES   32824
#define ID_STEP_VALUES_FORMAT_SIGNED    32825
#define ID_STEP_VALUES_FORMAT_TIES      32826
#define ID_STEP_VALUES_LAYOUT_COLS_STEPS 32827
#define ID_STEP_VALUES_LAYOUT_COLS_TRACKS 32828
#define ID_TOOLS_CHECK_MODULATIONS      32829
#define ID_TOOLS_CONVERGENCES           32830
#define ID_TOOLS_DEVICES                32831
#define ID_TOOLS_EXPORT_MODULATIONS     32832
#define ID_TOOLS_EXPORT_SONG            32833
#define ID_TOOLS_EXPORT_STEPS           32834
#define ID_TOOLS_EXPORT_TRACKS          32835
#define ID_TOOLS_IMPORT_MODULATIONS     32836
#define ID_TOOLS_IMPORT_STEPS           32837
#define ID_TOOLS_IMPORT_TRACKS          32838
#define ID_TOOLS_MIDI_LEARN             32839
#define ID_TOOLS_OPTIONS                32840
#define ID_TOOLS_PRIME_FACTORS          32841
#define ID_TOOLS_STATISTICS             32842
#define ID_TOOLS_TIME_TO_REPEAT         32843
#define ID_TOOLS_VELOCITY_RANGE         32844
#define ID_TRACK_COLOR                  32845
#define ID_TRACK_FILL                   32846
#define ID_TRACK_GROUP                  32847
#define ID_TRACK_INVERT                 32848
#define ID_TRACK_LENGTH                 32849
#define ID_TRACK_MODULATION             32850
#define ID_TRACK_MUTE                   32851
#define ID_TRACK_OFFSET                 32852
#define ID_TRACK_PART_CREATE            32853
#define ID_TRACK_PART_UPDATE            32854
#define ID_TRACK_PRESET_APPLY           32855
#define ID_TRACK_PRESET_CREATE          32856
#define ID_TRACK_PRESET_UPDATE          32857
#define ID_TRACK_REVERSE                32858
#define ID_TRACK_ROTATE_LEFT            32859
#define ID_TRACK_ROTATE_RIGHT           32860
#define ID_TRACK_ROTATE_STEPS           32861
#define ID_TRACK_SHIFT_LEFT             32862
#define ID_TRACK_SHIFT_RIGHT            32863
#define ID_TRACK_SHIFT_STEPS            32864
#define ID_TRACK_SOLO                   32865
#define ID_TRACK_SORT                   32866
#define ID_TRACK_STRETCH                32867
#define ID_TRACK_TIE_NOTES              32868
#define ID_TRACK_TRANSPOSE              32869
#define ID_TRACK_VELOCITY               32870
#define ID_TRANSPORT_CONVERGENCE_NEXT   32871
#define ID_TRANSPORT_CONVERGENCE_PREVIOUS 32872
#define ID_TRANSPORT_CONVERGENCE_SIZE_ALL 32873
#define ID_TRANSPORT_CONVERGENCE_SIZE_CUSTOM 32874
#define ID_TRANSPORT_GO_TO_POSITION     32875
#define ID_TRANSPORT_LOOP               32876
#define ID_TRANSPORT_PAUSE              32877
#define ID_TRANSPORT_PLAY               32878
#define ID_TRANSPORT_RECORD             32879
#define ID_TRANSPORT_RECORD_TRACKS      32880
#define ID_TRANSPORT_REWIND             32881
#define ID_VIEW_APPLOOK_OFF_2003        32882
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   32883
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  32884
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   32885
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 32886
#define ID_VIEW_APPLOOK_OFF_XP          32887
#define ID_VIEW_APPLOOK_VS_2005         32888
#define ID_VIEW_APPLOOK_VS_2008         32889
#define ID_VIEW_APPLOOK_WINDOWS_7       32890
#define ID_VIEW_APPLOOK_WIN_2000        32891
#define ID_VIEW_APPLOOK_WIN_XP          32892
#define ID_VIEW_BAR_Channels            32893
#define ID_VIEW_BAR_Graph               32894
#define ID_VIEW_BAR_Mapping             32895
#define ID_VIEW_BAR_MidiInput           32896
#define ID_VIEW_BAR_MidiOutput          32897
#define ID_VIEW_BAR_Modulations         32898
#define ID_VIEW_BAR_Parts               32899
#define ID_VIEW_BAR_Phase               32900
#define ID_VIEW_BAR_Piano               32901
#define ID_VIEW_BAR_Presets             32902
#define ID_VIEW_BAR_Properties          32903
#define ID_VIEW_BAR_StepValues          32904
#define ID_VIEW_CUSTOMIZE               32905
#define ID_VIEW_TYPE_LIVE               32906
#define ID_VIEW_TYPE_SONG               32907
#define ID_VIEW_TYPE_TRACK              32908
#define ID_VIEW_VELOCITIES              32909
#define ID_VIEW_ZOOM_IN                 32910
#define ID_VIEW_ZOOM_OUT                32911
#define ID_VIEW_ZOOM_RESET              32912
#define ID_WINDOW_FULL_SCREEN           32913
#define ID_WINDOW_MANAGER               32914
#define ID_WINDOW_NEW_HORZ_TAB_GROUP    32915
#define ID_WINDOW_NEW_VERT_TAB_GROUP    32916
#define ID_WINDOW_RESET_LAYOUT          32917

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        526
#define _APS_NEXT_COMMAND_VALUE         32918
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
