//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Polymeter.rc
//
#define IDR_MAINFRAME                   101
#define IDR_LIST_COL_HDR                102
#define IDR_MAINFRAME_256               103
#define IDR_PARTS_CTX                   104
#define IDR_POPUP_EDIT                  105
#define IDR_PRESETS_CTX                 106
#define IDR_PolymeterTYPE               107
#define IDR_THEME_MENU                  108
#define IDD_ABOUTBOX                    109
#define IDD_EXPORT                      110
#define IDD_GO_TO_POSITION              111
#define IDD_MASTER                      112
#define IDD_OFFSET                      113
#define IDD_OPTIONS                     114
#define IDD_PROGRESS                    115
#define IDD_TRACK_SORT                  116
#define IDS_APP_HELP_FILE_MISSING       200
#define IDS_APP_LICENSE                 201
#define IDS_APP_UNKNOWN_SYSTEM_ERROR    202
#define IDS_BAR_CHANNELS                203
#define IDS_BAR_MODULATIONS             204
#define IDS_BAR_PARTS                   205
#define IDS_BAR_PRESETS                 206
#define IDS_BAR_PROPERTIES              207
#define IDS_CHANNEL_COL_BankLSB         208
#define IDS_CHANNEL_COL_BankMSB         209
#define IDS_CHANNEL_COL_Number          210
#define IDS_CHANNEL_COL_Pan             211
#define IDS_CHANNEL_COL_Patch           212
#define IDS_CHANNEL_COL_Volume          213
#define IDS_CKUP_CANT_GET_ADDR          214
#define IDS_CKUP_CANT_LOAD_DLL          215
#define IDS_DOC_BAD_FORMAT              216
#define IDS_DOC_BAD_STEP_SELECTION      217
#define IDS_DOC_CANT_TRUNCATE_RECORDING 218
#define IDS_DOC_CLIP_WARNING            219
#define IDS_DOC_GROUP_OVERLAP           220
#define IDS_DOC_NEWER_VERSION           221
#define IDS_DOC_TRACK_TOO_LONG          222
#define IDS_DOC_VELOCITY_RANGE          223
#define IDS_EDIT_APPLY_PRESET           224
#define IDS_EDIT_CREATE_PART            225
#define IDS_EDIT_CREATE_PRESET          226
#define IDS_EDIT_CUT_STEPS              227
#define IDS_EDIT_CUT_TRACKS             228
#define IDS_EDIT_DELETE_PARTS           229
#define IDS_EDIT_DELETE_PRESETS         230
#define IDS_EDIT_DELETE_STEPS           231
#define IDS_EDIT_DELETE_TRACKS          232
#define IDS_EDIT_DUB                    233
#define IDS_EDIT_INSERT_STEPS           234
#define IDS_EDIT_INSERT_TRACKS          235
#define IDS_EDIT_MENU                   236
#define IDS_EDIT_MODULATION             237
#define IDS_EDIT_MOVE_PARTS             238
#define IDS_EDIT_MOVE_PRESETS           239
#define IDS_EDIT_MOVE_TRACKS            240
#define IDS_EDIT_MULTI_STEP_RECT        241
#define IDS_EDIT_PASTE_STEPS            242
#define IDS_EDIT_PASTE_TRACKS           243
#define IDS_EDIT_RECORD                 244
#define IDS_EDIT_REDO_FMT               245
#define IDS_EDIT_RENAME_PART            246
#define IDS_EDIT_RENAME_PRESET          247
#define IDS_EDIT_REVERSE                248
#define IDS_EDIT_ROTATE                 249
#define IDS_EDIT_SHIFT                  250
#define IDS_EDIT_SOLO                   251
#define IDS_EDIT_TRACK_SORT             252
#define IDS_EDIT_TRANSPOSE              253
#define IDS_EDIT_UNDO_FMT               254
#define IDS_EDIT_UPDATE_PART            255
#define IDS_EDIT_UPDATE_PRESET          256
#define IDS_EDIT_VELOCITY               257
#define IDS_ERR_TRACK_LENGTH_CURSOR     258
#define IDS_EXPORT                      259
#define IDS_EXPORT_BAD_DURATION         260
#define IDS_EXPORT_EMPTY_FILE           261
#define IDS_EXPORT_ERROR                262
#define IDS_EXPORT_FILE_FILTER          263
#define IDS_EXPORT_TOO_MANY_TRACKS      264
#define IDS_GRID_ERR_BAD_TIME_FORMAT    265
#define IDS_HLINK_CANT_LAUNCH           266
#define IDS_MIDI_DEVICES_MISSING        267
#define IDS_MIDI_INPUT                  268
#define IDS_MIDI_NO_OUTPUT_DEVICE       269
#define IDS_MIDI_OUTPUT                 270
#define IDS_MOD_SOURCE                  271
#define IDS_NONE                        272
#define IDS_OFFSET_NOTES                273
#define IDS_OFFSET_STEPS                274
#define IDS_OPT_DESC_General_bAlwaysRecord 275
#define IDS_OPT_DESC_General_bCheckForUpdates 276
#define IDS_OPT_DESC_General_bPropertyDescrips 277
#define IDS_OPT_DESC_Midi_bThru         278
#define IDS_OPT_DESC_Midi_iInputDevice  279
#define IDS_OPT_DESC_Midi_iOutputDevice 280
#define IDS_OPT_DESC_Midi_nBufferSize   281
#define IDS_OPT_DESC_Midi_nDefaultVelocity 282
#define IDS_OPT_DESC_Midi_nLatency      283
#define IDS_OPT_DESC_View_bShowCurPos   284
#define IDS_OPT_DESC_View_bShowGMNames  285
#define IDS_OPT_DESC_View_bShowNoteNames 286
#define IDS_OPT_DESC_View_fUpdateFreq   287
#define IDS_OPT_DESC_View_fZoomDelta    288
#define IDS_OPT_DESC_View_nLiveFontHeight 289
#define IDS_OPT_GROUP_General           290
#define IDS_OPT_GROUP_Midi              291
#define IDS_OPT_GROUP_View              292
#define IDS_OPT_NAME_General_bAlwaysRecord 293
#define IDS_OPT_NAME_General_bCheckForUpdates 294
#define IDS_OPT_NAME_General_bPropertyDescrips 295
#define IDS_OPT_NAME_Midi_bThru         296
#define IDS_OPT_NAME_Midi_iInputDevice  297
#define IDS_OPT_NAME_Midi_iOutputDevice 298
#define IDS_OPT_NAME_Midi_nBufferSize   299
#define IDS_OPT_NAME_Midi_nDefaultVelocity 300
#define IDS_OPT_NAME_Midi_nLatency      301
#define IDS_OPT_NAME_View_bShowCurPos   302
#define IDS_OPT_NAME_View_bShowGMNames  303
#define IDS_OPT_NAME_View_bShowNoteNames 304
#define IDS_OPT_NAME_View_fUpdateFreq   305
#define IDS_OPT_NAME_View_fZoomDelta    306
#define IDS_OPT_NAME_View_nLiveFontHeight 307
#define IDS_PDR_DESC_fTempo             308
#define IDS_PDR_DESC_nKeySig            309
#define IDS_PDR_DESC_nMeter             310
#define IDS_PDR_DESC_nSongLength        311
#define IDS_PDR_DESC_nStartPos          312
#define IDS_PDR_DESC_nTimeDiv           313
#define IDS_PDR_GROUP_Master            314
#define IDS_PDR_NAME_fTempo             315
#define IDS_PDR_NAME_nKeySig            316
#define IDS_PDR_NAME_nMeter             317
#define IDS_PDR_NAME_nSongLength        318
#define IDS_PDR_NAME_nStartPos          319
#define IDS_PDR_NAME_nTimeDiv           320
#define IDS_PROPS_MORE_COLORS           321
#define IDS_RESET_ALL_OPTIONS           322
#define IDS_SEQERR_BAD_TIME_FORMAT      323
#define IDS_SEQERR_BUFFER_OVERRUN       324
#define IDS_SEQ_MIDI_ERROR              325
#define IDS_SORT_DIR_ASCENDING          326
#define IDS_SORT_DIR_DESCENDING         327
#define IDS_STATUS_PANE1                328
#define IDS_STATUS_PANE2                329
#define IDS_TIME_TO_REPEAT_DAYS         330
#define IDS_TIME_TO_REPEAT_FMT          331
#define IDS_TOOLBAR_CUSTOMIZE           332
#define IDS_TOOLBAR_STANDARD            333
#define IDS_TRACK_TYPE_CHAN_AFT         334
#define IDS_TRACK_TYPE_CONTROL          335
#define IDS_TRACK_TYPE_KEY_AFT          336
#define IDS_TRACK_TYPE_MODULATOR        337
#define IDS_TRACK_TYPE_NOTE             338
#define IDS_TRACK_TYPE_PATCH            339
#define IDS_TRACK_TYPE_WHEEL            340
#define IDS_TRK_Channel                 341
#define IDS_TRK_Duration                342
#define IDS_TRK_Length                  343
#define IDS_TRK_Mute                    344
#define IDS_TRK_Name                    345
#define IDS_TRK_Note                    346
#define IDS_TRK_Number                  347
#define IDS_TRK_Offset                  348
#define IDS_TRK_Quant                   349
#define IDS_TRK_STEP                    350
#define IDS_TRK_Swing                   351
#define IDS_TRK_Type                    352
#define IDS_TRK_Velocity                353
#define IDS_TYPE_TRACK                  354
#define IDP_OLE_INIT_FAILED             355
#define IDC_ABOUT_LICENSE               1001
#define IDC_ABOUT_VERSION               1002
#define IDC_CURSOR_DRAG_MULTI           1003
#define IDC_CURSOR_DRAG_SINGLE          1004
#define IDC_EXPORT_DURATION             1005
#define IDC_GO_TO_POS_EDIT              1006
#define IDC_MASTER_OUT_DEVICE           1007
#define IDC_MASTER_TEMPO                1008
#define IDC_OFFSET_CAPTION              1009
#define IDC_OFFSET_EDIT                 1010
#define IDC_OFFSET_SPIN                 1011
#define IDC_OPTIONS_GRID                1012
#define IDC_OPTIONS_RESET_ALL           1013
#define IDC_PROGRESS                    1014
#define IDC_PROGRESS_PERCENT            1015
#define IDC_TRACK_SORT_DIR1             1016
#define IDC_TRACK_SORT_DIR2             1017
#define IDC_TRACK_SORT_DIR3             1018
#define IDC_TRACK_SORT_PROP1            1019
#define IDC_TRACK_SORT_PROP2            1020
#define IDC_TRACK_SORT_PROP3            1021
#define ID_APP_CHECK_FOR_UPDATES        32771
#define ID_APP_HOME_PAGE                32772
#define ID_EDIT_DELETE                  32773
#define ID_EDIT_INSERT                  32774
#define ID_EDIT_RENAME                  32775
#define ID_FILE_EXPORT                  32776
#define ID_INDICATOR_SONG_POS           32777
#define ID_INDICATOR_SONG_TIME          32778
#define ID_LIST_COL_HDR_RESET           32779
#define ID_TOOLS_DEVICES                32780
#define ID_TOOLS_OPTIONS                32781
#define ID_TOOLS_STATISTICS             32782
#define ID_TOOLS_TIME_TO_REPEAT         32783
#define ID_TOOLS_VELOCITY_RANGE         32784
#define ID_TRACK_GROUP                  32785
#define ID_TRACK_LENGTH                 32786
#define ID_TRACK_MUTE                   32787
#define ID_TRACK_PART_CREATE            32788
#define ID_TRACK_PART_UPDATE            32789
#define ID_TRACK_PRESET_APPLY           32790
#define ID_TRACK_PRESET_CREATE          32791
#define ID_TRACK_PRESET_UPDATE          32792
#define ID_TRACK_REVERSE                32793
#define ID_TRACK_ROTATE_LEFT            32794
#define ID_TRACK_ROTATE_RIGHT           32795
#define ID_TRACK_ROTATE_STEPS           32796
#define ID_TRACK_SHIFT_LEFT             32797
#define ID_TRACK_SHIFT_RIGHT            32798
#define ID_TRACK_SHIFT_STEPS            32799
#define ID_TRACK_SOLO                   32800
#define ID_TRACK_SORT                   32801
#define ID_TRACK_TIE_NOTES              32802
#define ID_TRACK_TRANSPOSE              32803
#define ID_TRACK_VELOCITY               32804
#define ID_TRANSPORT_GO_TO_POSITION     32805
#define ID_TRANSPORT_PAUSE              32806
#define ID_TRANSPORT_PLAY               32807
#define ID_TRANSPORT_RECORD             32808
#define ID_TRANSPORT_REWIND             32809
#define ID_VIEW_APPLOOK_OFF_2003        32810
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   32811
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  32812
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   32813
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 32814
#define ID_VIEW_APPLOOK_OFF_XP          32815
#define ID_VIEW_APPLOOK_VS_2005         32816
#define ID_VIEW_APPLOOK_VS_2008         32817
#define ID_VIEW_APPLOOK_WINDOWS_7       32818
#define ID_VIEW_APPLOOK_WIN_2000        32819
#define ID_VIEW_APPLOOK_WIN_XP          32820
#define ID_VIEW_CHANNELS                32821
#define ID_VIEW_CUSTOMIZE               32822
#define ID_VIEW_MODULATIONS             32823
#define ID_VIEW_PARTS                   32824
#define ID_VIEW_PRESETS                 32825
#define ID_VIEW_PROPERTIES              32826
#define ID_VIEW_TYPE_LIVE               32827
#define ID_VIEW_TYPE_SONG               32828
#define ID_VIEW_TYPE_TRACK              32829
#define ID_VIEW_VELOCITIES              32830
#define ID_VIEW_ZOOM_IN                 32831
#define ID_VIEW_ZOOM_OUT                32832
#define ID_VIEW_ZOOM_RESET              32833
#define ID_WINDOW_FULL_SCREEN           32834
#define ID_WINDOW_MANAGER               32835

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        356
#define _APS_NEXT_COMMAND_VALUE         32836
#define _APS_NEXT_CONTROL_VALUE         1022
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
