//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Polymeter.rc
//
#define IDR_MAINFRAME                   101
#define IDR_LIST_COL_HDR                102
#define IDR_MAINFRAME_256               103
#define IDR_MODULATION_CTX              104
#define IDR_PARTS_CTX                   105
#define IDR_POPUP_EDIT                  106
#define IDR_PRESETS_CTX                 107
#define IDR_PolymeterTYPE               108
#define IDR_THEME_MENU                  109
#define IDD_ABOUTBOX                    110
#define IDD_EXPORT                      111
#define IDD_FILL                        112
#define IDD_GO_TO_POSITION              113
#define IDD_MASTER                      114
#define IDD_OFFSET                      115
#define IDD_OPTIONS                     116
#define IDD_PROGRESS                    117
#define IDD_STRETCH                     118
#define IDD_TRACK_SORT                  119
#define IDD_VELOCITY_OFFSET             120
#define IDD_VELOCITY_SCALE              121
#define IDS_APP_HELP_FILE_MISSING       200
#define IDS_APP_LICENSE                 201
#define IDS_APP_UNKNOWN_SYSTEM_ERROR    202
#define IDS_BAR_CHANNELS                203
#define IDS_BAR_MODULATIONS             204
#define IDS_BAR_PARTS                   205
#define IDS_BAR_PRESETS                 206
#define IDS_BAR_PROPERTIES              207
#define IDS_CHANNEL_COL_BankLSB         208
#define IDS_CHANNEL_COL_BankMSB         209
#define IDS_CHANNEL_COL_Number          210
#define IDS_CHANNEL_COL_Pan             211
#define IDS_CHANNEL_COL_Patch           212
#define IDS_CHANNEL_COL_Volume          213
#define IDS_CKUP_CANT_GET_ADDR          214
#define IDS_CKUP_CANT_LOAD_DLL          215
#define IDS_DOC_BAD_FORMAT              216
#define IDS_DOC_BAD_STEP_SELECTION      217
#define IDS_DOC_CANT_TRUNCATE_RECORDING 218
#define IDS_DOC_CLIP_WARNING            219
#define IDS_DOC_GROUP_OVERLAP           220
#define IDS_DOC_NEWER_VERSION           221
#define IDS_DOC_TRACK_TOO_LONG          222
#define IDS_DOC_VELOCITY_RANGE          223
#define IDS_EDIT_APPLY_PRESET           224
#define IDS_EDIT_CREATE_PART            225
#define IDS_EDIT_CREATE_PRESET          226
#define IDS_EDIT_CUT_STEPS              227
#define IDS_EDIT_CUT_TRACKS             228
#define IDS_EDIT_DELETE_PARTS           229
#define IDS_EDIT_DELETE_PRESETS         230
#define IDS_EDIT_DELETE_STEPS           231
#define IDS_EDIT_DELETE_TRACKS          232
#define IDS_EDIT_DUB                    233
#define IDS_EDIT_FILL_STEPS             234
#define IDS_EDIT_INSERT_STEPS           235
#define IDS_EDIT_INSERT_TRACKS          236
#define IDS_EDIT_MENU                   237
#define IDS_EDIT_MODULATION             238
#define IDS_EDIT_MOVE_PARTS             239
#define IDS_EDIT_MOVE_PRESETS           240
#define IDS_EDIT_MOVE_TRACKS            241
#define IDS_EDIT_MULTI_STEP_RECT        242
#define IDS_EDIT_PASTE_STEPS            243
#define IDS_EDIT_PASTE_TRACKS           244
#define IDS_EDIT_RECORD                 245
#define IDS_EDIT_REDO_FMT               246
#define IDS_EDIT_RENAME_PART            247
#define IDS_EDIT_RENAME_PRESET          248
#define IDS_EDIT_REVERSE                249
#define IDS_EDIT_ROTATE                 250
#define IDS_EDIT_SHIFT                  251
#define IDS_EDIT_SOLO                   252
#define IDS_EDIT_TRACK_SORT             253
#define IDS_EDIT_TRANSPOSE              254
#define IDS_EDIT_UNDO_FMT               255
#define IDS_EDIT_UPDATE_PART            256
#define IDS_EDIT_UPDATE_PRESET          257
#define IDS_EDIT_VELOCITY               258
#define IDS_ERR_TRACK_LENGTH_CURSOR     259
#define IDS_EXPORT                      260
#define IDS_EXPORT_BAD_DURATION         261
#define IDS_EXPORT_EMPTY_FILE           262
#define IDS_EXPORT_ERROR                263
#define IDS_EXPORT_FILE_FILTER          264
#define IDS_EXPORT_TOO_MANY_TRACKS      265
#define IDS_GRID_ERR_BAD_TIME_FORMAT    266
#define IDS_HLINK_CANT_LAUNCH           267
#define IDS_IMPORT                      268
#define IDS_MIDI_DEVICES_MISSING        269
#define IDS_MIDI_INPUT                  270
#define IDS_MIDI_NO_OUTPUT_DEVICE       271
#define IDS_MIDI_OUTPUT                 272
#define IDS_MOD_DIFFERENCES             273
#define IDS_MOD_SOURCE                  274
#define IDS_NONE                        275
#define IDS_OFFSET_NOTES                276
#define IDS_OFFSET_STEPS                277
#define IDS_OPT_DESC_General_bAlwaysRecord 278
#define IDS_OPT_DESC_General_bCheckForUpdates 279
#define IDS_OPT_DESC_General_bPropertyDescrips 280
#define IDS_OPT_DESC_General_iInputQuant 281
#define IDS_OPT_DESC_Midi_bThru         282
#define IDS_OPT_DESC_Midi_iInputDevice  283
#define IDS_OPT_DESC_Midi_iOutputDevice 284
#define IDS_OPT_DESC_Midi_nBufferSize   285
#define IDS_OPT_DESC_Midi_nDefaultVelocity 286
#define IDS_OPT_DESC_Midi_nLatency      287
#define IDS_OPT_DESC_View_bShowCurPos   288
#define IDS_OPT_DESC_View_bShowGMNames  289
#define IDS_OPT_DESC_View_bShowNoteNames 290
#define IDS_OPT_DESC_View_fUpdateFreq   291
#define IDS_OPT_DESC_View_fZoomDelta    292
#define IDS_OPT_DESC_View_nLiveFontHeight 293
#define IDS_OPT_GROUP_General           294
#define IDS_OPT_GROUP_Midi              295
#define IDS_OPT_GROUP_View              296
#define IDS_OPT_NAME_General_bAlwaysRecord 297
#define IDS_OPT_NAME_General_bCheckForUpdates 298
#define IDS_OPT_NAME_General_bPropertyDescrips 299
#define IDS_OPT_NAME_General_iInputQuant 300
#define IDS_OPT_NAME_Midi_bThru         301
#define IDS_OPT_NAME_Midi_iInputDevice  302
#define IDS_OPT_NAME_Midi_iOutputDevice 303
#define IDS_OPT_NAME_Midi_nBufferSize   304
#define IDS_OPT_NAME_Midi_nDefaultVelocity 305
#define IDS_OPT_NAME_Midi_nLatency      306
#define IDS_OPT_NAME_View_bShowCurPos   307
#define IDS_OPT_NAME_View_bShowGMNames  308
#define IDS_OPT_NAME_View_bShowNoteNames 309
#define IDS_OPT_NAME_View_fUpdateFreq   310
#define IDS_OPT_NAME_View_fZoomDelta    311
#define IDS_OPT_NAME_View_nLiveFontHeight 312
#define IDS_PDR_DESC_fTempo             313
#define IDS_PDR_DESC_nKeySig            314
#define IDS_PDR_DESC_nMeter             315
#define IDS_PDR_DESC_nSongLength        316
#define IDS_PDR_DESC_nStartPos          317
#define IDS_PDR_DESC_nTimeDiv           318
#define IDS_PDR_GROUP_Master            319
#define IDS_PDR_NAME_fTempo             320
#define IDS_PDR_NAME_nKeySig            321
#define IDS_PDR_NAME_nMeter             322
#define IDS_PDR_NAME_nSongLength        323
#define IDS_PDR_NAME_nStartPos          324
#define IDS_PDR_NAME_nTimeDiv           325
#define IDS_PROPS_MORE_COLORS           326
#define IDS_RESET_ALL_OPTIONS           327
#define IDS_SEQERR_BAD_TIME_FORMAT      328
#define IDS_SEQERR_BUFFER_OVERRUN       329
#define IDS_SEQERR_TOO_MANY_RECURSIONS  330
#define IDS_SEQ_MIDI_ERROR              331
#define IDS_SORT_DIR_ASCENDING          332
#define IDS_SORT_DIR_DESCENDING         333
#define IDS_STATUS_PANE1                334
#define IDS_STATUS_PANE2                335
#define IDS_TIME_TO_REPEAT_DAYS         336
#define IDS_TIME_TO_REPEAT_FMT          337
#define IDS_TOOLBAR_CUSTOMIZE           338
#define IDS_TOOLBAR_STANDARD            339
#define IDS_TRACK_TYPE_CHAN_AFT         340
#define IDS_TRACK_TYPE_CONTROL          341
#define IDS_TRACK_TYPE_KEY_AFT          342
#define IDS_TRACK_TYPE_MODULATOR        343
#define IDS_TRACK_TYPE_NOTE             344
#define IDS_TRACK_TYPE_PATCH            345
#define IDS_TRACK_TYPE_WHEEL            346
#define IDS_TRK_Channel                 347
#define IDS_TRK_Duration                348
#define IDS_TRK_Length                  349
#define IDS_TRK_Mute                    350
#define IDS_TRK_Name                    351
#define IDS_TRK_Note                    352
#define IDS_TRK_Number                  353
#define IDS_TRK_Offset                  354
#define IDS_TRK_Quant                   355
#define IDS_TRK_STEP                    356
#define IDS_TRK_Swing                   357
#define IDS_TRK_Type                    358
#define IDS_TRK_Velocity                359
#define IDS_TYPE_TRACK                  360
#define IDS_VELOCITY                    361
#define IDP_OLE_INIT_FAILED             362
#define IDC_ABOUT_LICENSE               1001
#define IDC_ABOUT_VERSION               1002
#define IDC_CURSOR_DRAG_MULTI           1003
#define IDC_CURSOR_DRAG_SINGLE          1004
#define IDC_EXPORT_DURATION             1005
#define IDC_FILL_CURVINESS              1006
#define IDC_FILL_FREQUENCY              1007
#define IDC_FILL_FUNCTION               1008
#define IDC_FILL_PHASE                  1009
#define IDC_FILL_SIGNED1                1010
#define IDC_FILL_SIGNED2                1011
#define IDC_FILL_STEP_END               1012
#define IDC_FILL_STEP_START             1013
#define IDC_FILL_VALUE_END              1014
#define IDC_FILL_VALUE_START            1015
#define IDC_GO_TO_POS_EDIT              1016
#define IDC_MASTER_OUT_DEVICE           1017
#define IDC_MASTER_TEMPO                1018
#define IDC_OFFSET_CAPTION              1019
#define IDC_OFFSET_EDIT                 1020
#define IDC_OFFSET_SPIN                 1021
#define IDC_OPTIONS_GRID                1022
#define IDC_OPTIONS_RESET_ALL           1023
#define IDC_PROGRESS                    1024
#define IDC_PROGRESS_PERCENT            1025
#define IDC_STRETCH_CAPTION             1026
#define IDC_STRETCH_EDIT                1027
#define IDC_TRACK_SORT_DIR1             1028
#define IDC_TRACK_SORT_DIR2             1029
#define IDC_TRACK_SORT_DIR3             1030
#define IDC_TRACK_SORT_PROP1            1031
#define IDC_TRACK_SORT_PROP2            1032
#define IDC_TRACK_SORT_PROP3            1033
#define IDC_VELOCITY_OFFSET_EDIT        1034
#define IDC_VELOCITY_OFFSET_TARGET      1035
#define IDC_VELOCITY_OFFSET_TARGET2     1036
#define IDC_VELOCITY_SCALE_EDIT         1037
#define ID_APP_CHECK_FOR_UPDATES        32771
#define ID_APP_HOME_PAGE                32772
#define ID_EDIT_DELETE                  32773
#define ID_EDIT_DESELECT                32774
#define ID_EDIT_INSERT                  32775
#define ID_EDIT_RENAME                  32776
#define ID_FILE_EXPORT                  32777
#define ID_FILE_IMPORT                  32778
#define ID_INDICATOR_SONG_POS           32779
#define ID_INDICATOR_SONG_TIME          32780
#define ID_LIST_COL_HDR_RESET           32781
#define ID_MODULATION_SHOW_DIFFERENCES  32782
#define ID_PARTS_SELECT_TRACKS          32783
#define ID_TOOLS_DEVICES                32784
#define ID_TOOLS_OPTIONS                32785
#define ID_TOOLS_STATISTICS             32786
#define ID_TOOLS_TIME_TO_REPEAT         32787
#define ID_TOOLS_VELOCITY_RANGE         32788
#define ID_TRACK_FILL                   32789
#define ID_TRACK_GROUP                  32790
#define ID_TRACK_LENGTH                 32791
#define ID_TRACK_MUTE                   32792
#define ID_TRACK_PART_CREATE            32793
#define ID_TRACK_PART_UPDATE            32794
#define ID_TRACK_PRESET_APPLY           32795
#define ID_TRACK_PRESET_CREATE          32796
#define ID_TRACK_PRESET_UPDATE          32797
#define ID_TRACK_REVERSE                32798
#define ID_TRACK_ROTATE_LEFT            32799
#define ID_TRACK_ROTATE_RIGHT           32800
#define ID_TRACK_ROTATE_STEPS           32801
#define ID_TRACK_SHIFT_LEFT             32802
#define ID_TRACK_SHIFT_RIGHT            32803
#define ID_TRACK_SHIFT_STEPS            32804
#define ID_TRACK_SOLO                   32805
#define ID_TRACK_SORT                   32806
#define ID_TRACK_STRETCH                32807
#define ID_TRACK_TIE_NOTES              32808
#define ID_TRACK_TRANSPOSE              32809
#define ID_TRACK_VELOCITY               32810
#define ID_TRANSPORT_GO_TO_POSITION     32811
#define ID_TRANSPORT_PAUSE              32812
#define ID_TRANSPORT_PLAY               32813
#define ID_TRANSPORT_RECORD             32814
#define ID_TRANSPORT_REWIND             32815
#define ID_VIEW_APPLOOK_OFF_2003        32816
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   32817
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  32818
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   32819
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 32820
#define ID_VIEW_APPLOOK_OFF_XP          32821
#define ID_VIEW_APPLOOK_VS_2005         32822
#define ID_VIEW_APPLOOK_VS_2008         32823
#define ID_VIEW_APPLOOK_WINDOWS_7       32824
#define ID_VIEW_APPLOOK_WIN_2000        32825
#define ID_VIEW_APPLOOK_WIN_XP          32826
#define ID_VIEW_CHANNELS                32827
#define ID_VIEW_CUSTOMIZE               32828
#define ID_VIEW_MODULATIONS             32829
#define ID_VIEW_PARTS                   32830
#define ID_VIEW_PRESETS                 32831
#define ID_VIEW_PROPERTIES              32832
#define ID_VIEW_TYPE_LIVE               32833
#define ID_VIEW_TYPE_SONG               32834
#define ID_VIEW_TYPE_TRACK              32835
#define ID_VIEW_VELOCITIES              32836
#define ID_VIEW_ZOOM_IN                 32837
#define ID_VIEW_ZOOM_OUT                32838
#define ID_VIEW_ZOOM_RESET              32839
#define ID_WINDOW_FULL_SCREEN           32840
#define ID_WINDOW_MANAGER               32841

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        363
#define _APS_NEXT_COMMAND_VALUE         32842
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
