// Copyleft 2018 Chris Korda
// This program is free software; you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation; either version 2 of the License, or any later version.
/*
        chris korda
 
		revision history:
		rev		date	comments
        00      26mar18	initial version

		undo code data
 
*/

UCODE_DEF(TRACK_PROP)
UCODE_DEF(MULTI_TRACK_PROP)
UCODE_DEF(TRACK_STEP)
UCODE_DEF(MASTER_PROP)
UCODE_DEF(CUT_TRACKS)
UCODE_DEF(PASTE_TRACKS)
UCODE_DEF(INSERT_TRACKS)
UCODE_DEF(DELETE_TRACKS)
UCODE_DEF(MOVE_TRACKS)
UCODE_DEF(CHANNEL_PROP)
UCODE_DEF(MULTI_CHANNEL_PROP)
UCODE_DEF(TRACK_SORT)
UCODE_DEF(MULTI_STEP_RECT)
UCODE_DEF(CUT_STEPS)
UCODE_DEF(PASTE_STEPS)
UCODE_DEF(INSERT_STEPS)
UCODE_DEF(DELETE_STEPS)
UCODE_DEF(VELOCITY)
UCODE_DEF(REVERSE)
UCODE_DEF(REVERSE_RECT)
UCODE_DEF(ROTATE)
UCODE_DEF(ROTATE_RECT)
UCODE_DEF(SHIFT)
UCODE_DEF(SHIFT_RECT)
UCODE_DEF(DUB)
UCODE_DEF(RECORD)
UCODE_DEF(MUTE)
UCODE_DEF(SOLO)
UCODE_DEF(APPLY_PRESET)
UCODE_DEF(CREATE_PRESET)
UCODE_DEF(RENAME_PRESET)
UCODE_DEF(DELETE_PRESETS)
UCODE_DEF(MOVE_PRESETS)

#undef UCODE_DEF
