// Copyleft 2018 Chris Korda
// This program is free software; you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation; either version 2 of the License, or any later version.
/*
        chris korda
 
		revision history:
		rev		date	comments
        00      26mar18	initial version
		01		28nov18	add modify parts
		02		22mar19	add invert
		03		20mar20	add mapping
		04		28mar20	add learn multiple mappings
		05		07apr20	add move steps
		06		28sep20	add sort parts
		07		16nov20	add time division
		08		16dec20	add loop range

		undo code data
 
*/

UCODE_DEF(TRACK_PROP)
UCODE_DEF(MULTI_TRACK_PROP)
UCODE_DEF(TRACK_STEP)
UCODE_DEF(MASTER_PROP)
UCODE_DEF(CUT_TRACKS)
UCODE_DEF(PASTE_TRACKS)
UCODE_DEF(INSERT_TRACKS)
UCODE_DEF(DELETE_TRACKS)
UCODE_DEF(MOVE_TRACKS)
UCODE_DEF(CHANNEL_PROP)
UCODE_DEF(MULTI_CHANNEL_PROP)
UCODE_DEF(TRACK_SORT)
UCODE_DEF(MULTI_STEP_RECT)
UCODE_DEF(CUT_STEPS)
UCODE_DEF(PASTE_STEPS)
UCODE_DEF(INSERT_STEPS)
UCODE_DEF(DELETE_STEPS)
UCODE_DEF(MOVE_STEPS)
UCODE_DEF(VELOCITY)
UCODE_DEF(VELOCITY_RECT)
UCODE_DEF(REVERSE)
UCODE_DEF(REVERSE_RECT)
UCODE_DEF(ROTATE)
UCODE_DEF(ROTATE_RECT)
UCODE_DEF(SHIFT)
UCODE_DEF(SHIFT_RECT)
UCODE_DEF(DUB)
UCODE_DEF(RECORD)
UCODE_DEF(MUTE)
UCODE_DEF(SOLO)
UCODE_DEF(APPLY_PRESET)
UCODE_DEF(CREATE_PRESET)
UCODE_DEF(UPDATE_PRESET)
UCODE_DEF(RENAME_PRESET)
UCODE_DEF(DELETE_PRESETS)
UCODE_DEF(MOVE_PRESETS)
UCODE_DEF(CREATE_PART)
UCODE_DEF(UPDATE_PART)
UCODE_DEF(RENAME_PART)
UCODE_DEF(DELETE_PARTS)
UCODE_DEF(MOVE_PARTS)
UCODE_DEF(MODIFY_PARTS)
UCODE_DEF(SORT_PARTS)
UCODE_DEF(MODULATION)
UCODE_DEF(FILL_STEPS)
UCODE_DEF(INVERT)
UCODE_DEF(MAPPING_PROP)
UCODE_DEF(MULTI_MAPPING_PROP)
UCODE_DEF(CUT_MAPPINGS)
UCODE_DEF(PASTE_MAPPINGS)
UCODE_DEF(INSERT_MAPPING)
UCODE_DEF(DELETE_MAPPINGS)
UCODE_DEF(MOVE_MAPPINGS)
UCODE_DEF(SORT_MAPPINGS)
UCODE_DEF(LEARN_MAPPING)
UCODE_DEF(LEARN_MULTI_MAPPING)
UCODE_DEF(TIME_DIVISION)
UCODE_DEF(LOOP_RANGE)

#undef UCODE_DEF
